services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1499:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=sa123$..A"

  redis:
    image: redis
    ports:
      - "6379:6379"

  docker-tutorial:
    image: my-dotnet-image
    ports:
      - "8080:8080"
    environment:
      - "ConnectionStrings__ApplicationDb=${ApplicationDB}"
      - "ConnectionStrings__MyRedisConStr=${RedisDB}"
    depends_on:
      - db
      - redis
